[build]
  publish = "public"
  command = "yarn build"

[[redirects]]
  from = "/handbook/*"
  to = "https://handbook.suncoast.io"

[[redirects]]
  from = "https://demoday.suncoast.io"
  to = "https://suncoast.io/grads"

[[redirects]]
  from = "https://demoday.suncoast.io"
  to = "https://suncoast.io/grads"

[[redirects]]
  from = "/demo-day/*"
  to = "https://suncoast.io/grads"

[[redirects]]
  from = "/conference/*"
  to = "https://sdg-conf.netlify.app/:splat"
  status = 200
  force = true
