[build]
  publish = "public"
  command = "yarn build"

[[redirects]]
  from = "/handbook/*"
  to = "https://handbook.suncoast.io"

[[redirects]]
  from = "https://demoday.suncoast.io"
  to = "https://suncoast.io/demo-day"

[[redirects]]
  from = "https://demoday.suncoast.io"
  to = "https://suncoast.io/demo-day"